### ISSUE TITLE
TANGO broken after mcib3d-core update

### ISSUE THREAD

**Issue by landowark** [salsaj-boudier/TANGO#7]
There's a problem with TANGO recently and I"m thinking that the update to mcib3d-core is the issue. TANGO does not seem to be able to access mcib3d.image3d.processing.BinaryMorpho.binaryDilate anymore which is leading to an error out when running batch.

Specifically the error I'm receiving is:

Nuclei segmentation: 1/1
Exception in thread "Thread-6" java.lang.NoSuchMethodError: mcib3d.image3d.processing.BinaryMorpho.binaryDilate(Lmcib3d/image3d/ImageInt;FFI)Lmcib3d/image3d/ImageByte;
	at tango.plugin.filter.BinaryDilate.runPostFilter(BinaryDilate.java:82)
	at tango.plugin.filter.MorphoMathFilters.runPostFilter(MorphoMathFilters.java:75)
	at tango.plugin.filter.PostFilterSequence.run(PostFilterSequence.java:71)
	at tango.dataStructure.Field.postFilterStructure(Field.java:342)
	at tango.dataStructure.Field.processNucleus(Field.java:280)
	at tango.gui.FieldManager.processAndCropFields(FieldManager.java:126)
	at tango.gui.FieldManager.processAndCropFields(FieldManager.java:636)
	at tango.gui.FieldManager$2.run(FieldManager.java:601)
	at java.lang.Thread.run(Thread.java:748)

As an aside, the update for v0.98 is still providing the jar for v0.97 which is causing a duplication of commands.

**Comment by mcib3d** [comment]
Yes, there is a pb with the update of mcib3d, this commit a2e492d5af11ec8daec85596fc6480597c57e91b should fix the pb. The updated version of TANGO is updated on Fiji.

**Comment by landowark** [comment]
It seems to be working now, thanks.
